version: '3.4'

services:

  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - common

  catalogapi:
    image: catalogapi
    container_name: catalogapi
    build: backend/src/services/catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
    depends_on:
      - catalogdb
    ports:
      - 9000:80
    networks:
      - common


networks:
  common:
    name: dn-ecom-network
  

volumes:
  mongo_data: