version: '3.4'

services:

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: backend/src/services/catalog/Dockerfile


  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi    
    build: 
      context: .
      dockerfile: backend/src/services/basket/Dockerfile


networks:
  common:
    name: dn-ecom-network
  

volumes:
  mongo_data: