version: '3.4'

services:

  catalogdb:
    container_name: catalogdb-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - common

  basketdb:
    container_name: basketdb-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - common

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssword
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - common
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    networks:
      - common

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - common

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=p@ssword
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogapi:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
    depends_on:
      - catalogdb
    ports:
      - 9000:80
    networks:
      - common

  discountapi:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting__ConnectionString=Server=discountdb:5432;Database=DiscountDb;User Id=admin;Password=p@ssword"
    depends_on:
      - discountdb
    ports:
      - "9002:80"
    networks:
      - common

  basketapi:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discountapi"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
      - discountapi
    ports:
      - 9001:80
    networks:
      - common

  orderapi:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=P@ssword1;TrustServerCertificate=true"
    depends_on:
      - orderdb
    ports:
      - "9003:80"
    networks:
      - common

networks:
  common:
    name: dn-ecom-network
  

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data: