version: '3.4'

services:

  catalogdb:
    container_name: catalogdb-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - common

  basketdb:
    container_name: basketdb-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - common

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssword
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - common
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=p@ssword
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogapi:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
    depends_on:
      - catalogdb
    ports:
      - 9000:80
    networks:
      - common

  basketapi:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - 9001:80
    networks:
      - common

  discountapi:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting__ConnectionString=Server=discountdb:5432;Database=DiscountDb;User Id=admin;Password=p@ssword"
    depends_on:
      - discountdb
    ports:
      - "9002:80"
    networks:
      - common


networks:
  common:
    name: dn-ecom-network
  

volumes:
  mongo_data: